### ISSUE TITLE
update readme for the template

### ISSUE THREAD

**Issue by pacospace** [thoth-station/template-project#19]

**Comment by tlegen-k** [comment]
/assign @tlegen-k 
I would like to update the readme file

**Comment by pacospace** [comment]
> /assign @tlegen-k
> I would like to update the readme file

Thanks @tlegen-k, updates should be required in point 2, 3, 4.

I think point 2 we use prow with pre-commit and mypy, cc @KPostOffice 3 we don't use Zuul anymore, but AICOE-CI cc @harshad16, and 4 we have a public service now accessible to everyone, not only internally cc @fridex

**Comment by tlegen-k** [comment]
I think this issue was resolved by commit 26ad538 as it was in issue #22 "Update README.md" that was merged.

**Comment by pacospace** [comment]
Thanks @tlegen-k!!

**Comment by tlegen-k** [comment]
My pleasure!
