### ISSUE TITLE
More options for `This should yield a new module release`

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/template-project#34]
https://github.com/thoth-station/template-project/blob/122ec4e98e3a7d70bebeb97bb8658cc20e3124b8/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L19

Is the requirement for automation reasons or just a reference for repository maintainers? Nevertheless, wouldn't it be better to also include something like:

```
<!-- If this change modifies the behavior of the module, leave one of the following options -->
- patch
- minor
- major
```

?

**Comment by codificat** [comment]
> Is the requirement for automation reasons or just a reference for repository maintainers?

Tracking back the addition of that bit, the intention seems to be only to highlight it for humans to react: https://github.com/thoth-station/user-api/pull/1631#issuecomment-1025636528

> Nevertheless, wouldn't it be better to also include something like:

Anything that helps clarify the message is good!  PRs welcome :smiley:

**Comment by xtuchyna** [comment]
So I guess this https://github.com/thoth-station/kebechet/issues/711 works only by labeling the PR, right?

**Comment by KPostOffice** [comment]
@xtuchyna Yes exactly
