### ISSUE TITLE
shouldnt this be rhel?

### ISSUE THREAD

**Issue by goern** [thoth-station/template-project#6]
https://github.com/thoth-station/template-project/blob/552764fdb0e32d1e648054a6bf26a968edf9eb05/.thoth.yaml#L7-L9

**Comment by fridex** [comment]
One of the pipeline units on adviser side will map this to RHEL given the ABI compatibility in RHEL/UBI.

**Comment by goern** [comment]
is this still valid?

**Comment by fridex** [comment]
No longer valid. It can be RHEL/UBI - it will get remapped on Thoth side considering ABI compatibility.
